
am4core.ready(function () {

  // Themes begin
  // am4core.useTheme(am4themes_frozen);
  am4core.useTheme(am4themes_animated);
  // Themes end

  // Create chart instance
  var chart = am4core.create("chartdiv", am4charts.XYChart);

  // Add data
  chart.data = [{
    "Vuosi": 2018,
    "Kk": 11,
    "Pv": 11,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 5.4,
    "Ylin lämpötila (degC)": 5.8,
    "Alin lämpötila (degC)": 5.1
  },
  {
    "Vuosi": 2018,
    "Kk": 11,
    "Pv": 12,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 13.6,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 5.6,
    "Ylin lämpötila (degC)": 5.9,
    "Alin lämpötila (degC)": 5
  },
  {
    "Vuosi": 2018,
    "Kk": 11,
    "Pv": 13,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 3.7,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 6.6,
    "Ylin lämpötila (degC)": 8.3,
    "Alin lämpötila (degC)": 5.4
  },
  {
    "Vuosi": 2018,
    "Kk": 11,
    "Pv": 14,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 6.3,
    "Ylin lämpötila (degC)": 8.1,
    "Alin lämpötila (degC)": 4.4
  },
  {
    "Vuosi": 2018,
    "Kk": 11,
    "Pv": 15,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 7.9,
    "Ylin lämpötila (degC)": 9,
    "Alin lämpötila (degC)": 3
  },
  {
    "Vuosi": 2018,
    "Kk": 11,
    "Pv": 16,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 8.9,
    "Ylin lämpötila (degC)": 9.7,
    "Alin lämpötila (degC)": 8
  },
  {
    "Vuosi": 2018,
    "Kk": 11,
    "Pv": 17,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 6.8,
    "Ylin lämpötila (degC)": 9,
    "Alin lämpötila (degC)": 4.7
  },
  {
    "Vuosi": 2018,
    "Kk": 11,
    "Pv": 18,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 4.5,
    "Ylin lämpötila (degC)": 6.6,
    "Alin lämpötila (degC)": 3
  },
  {
    "Vuosi": 2018,
    "Kk": 11,
    "Pv": 19,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 0.4,
    "Ylin lämpötila (degC)": 3.1,
    "Alin lämpötila (degC)": -0.2
  },
  {
    "Vuosi": 2018,
    "Kk": 11,
    "Pv": 20,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 0,
    "Ylin lämpötila (degC)": 1.6,
    "Alin lämpötila (degC)": -2.5
  },
  {
    "Vuosi": 2018,
    "Kk": 11,
    "Pv": 21,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": "",
    "Ilman lämpötila (degC)": -0.7,
    "Ylin lämpötila (degC)": 1.9,
    "Alin lämpötila (degC)": -2.6
  },
  {
    "Vuosi": 2018,
    "Kk": 11,
    "Pv": 22,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": -0.5,
    "Ylin lämpötila (degC)": 1,
    "Alin lämpötila (degC)": -3.3
  },
  {
    "Vuosi": 2018,
    "Kk": 11,
    "Pv": 23,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 0.5,
    "Ylin lämpötila (degC)": 2.8,
    "Alin lämpötila (degC)": -2.2
  },
  {
    "Vuosi": 2018,
    "Kk": 11,
    "Pv": 24,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 0.2,
    "Ylin lämpötila (degC)": 2.2,
    "Alin lämpötila (degC)": -2.2
  },
  {
    "Vuosi": 2018,
    "Kk": 11,
    "Pv": 25,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": -4,
    "Ylin lämpötila (degC)": -1.8,
    "Alin lämpötila (degC)": -5.4
  },
  {
    "Vuosi": 2018,
    "Kk": 11,
    "Pv": 26,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": -2,
    "Ylin lämpötila (degC)": -0.2,
    "Alin lämpötila (degC)": -5.3
  },
  {
    "Vuosi": 2018,
    "Kk": 11,
    "Pv": 27,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": -3.6,
    "Ylin lämpötila (degC)": -1,
    "Alin lämpötila (degC)": -4.6
  },
  {
    "Vuosi": 2018,
    "Kk": 11,
    "Pv": 28,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.7,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": -3.2,
    "Ylin lämpötila (degC)": -0.8,
    "Alin lämpötila (degC)": -6.1
  },
  {
    "Vuosi": 2018,
    "Kk": 11,
    "Pv": 29,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 0.7,
    "Ylin lämpötila (degC)": 3,
    "Alin lämpötila (degC)": -1.4
  },
  {
    "Vuosi": 2018,
    "Kk": 11,
    "Pv": 30,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 1.6,
    "Ylin lämpötila (degC)": 2.3,
    "Alin lämpötila (degC)": -0.1
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 1,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": -0.7,
    "Ylin lämpötila (degC)": 2.3,
    "Alin lämpötila (degC)": -2.2
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 2,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": -0.6,
    "Ylin lämpötila (degC)": 0.2,
    "Alin lämpötila (degC)": -1.4
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 3,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 1.9,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": -0.2,
    "Ylin lämpötila (degC)": 0.5,
    "Alin lämpötila (degC)": -1.1
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 4,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 4,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 4,
    "Ylin lämpötila (degC)": 5.7,
    "Alin lämpötila (degC)": -0.1
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 5,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.4,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 2.9,
    "Ylin lämpötila (degC)": 5.8,
    "Alin lämpötila (degC)": 1.2
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 6,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 0.6,
    "Ylin lämpötila (degC)": 2.6,
    "Alin lämpötila (degC)": -1.5
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 7,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 3.1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 1.3,
    "Ylin lämpötila (degC)": 3.8,
    "Alin lämpötila (degC)": -2.1
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 8,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 16.7,
    "Lumensyvyys (cm)": 0,
    "Ilman lämpötila (degC)": 2.4,
    "Ylin lämpötila (degC)": 3.5,
    "Alin lämpötila (degC)": 0.1
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 9,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.8,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 4.5,
    "Ylin lämpötila (degC)": 5.5,
    "Alin lämpötila (degC)": 3.6
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 10,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 2.8,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 2.9,
    "Ylin lämpötila (degC)": 4.2,
    "Alin lämpötila (degC)": 2.3
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 11,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.2,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 1.2,
    "Ylin lämpötila (degC)": 2.3,
    "Alin lämpötila (degC)": 0.5
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 12,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 0.1,
    "Ylin lämpötila (degC)": 1.1,
    "Alin lämpötila (degC)": -0.8
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 13,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": -1.3,
    "Ylin lämpötila (degC)": 0.1,
    "Alin lämpötila (degC)": -1.5
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 14,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": -3.7,
    "Ylin lämpötila (degC)": -1.5,
    "Alin lämpötila (degC)": -4.2
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 15,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": -5.1,
    "Ylin lämpötila (degC)": -4.1,
    "Alin lämpötila (degC)": -5.6
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 16,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 3.1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": -3.5,
    "Ylin lämpötila (degC)": -0.7,
    "Alin lämpötila (degC)": -5.7
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 17,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 1.9,
    "Lumensyvyys (cm)": 2,
    "Ilman lämpötila (degC)": 0.2,
    "Ylin lämpötila (degC)": 0.8,
    "Alin lämpötila (degC)": -0.8
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 18,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.5,
    "Lumensyvyys (cm)": 5,
    "Ilman lämpötila (degC)": 1.4,
    "Ylin lämpötila (degC)": 1.8,
    "Alin lämpötila (degC)": 0.7
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 19,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.4,
    "Lumensyvyys (cm)": 3,
    "Ilman lämpötila (degC)": 0.8,
    "Ylin lämpötila (degC)": 2.1,
    "Alin lämpötila (degC)": 0.2
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 20,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 3,
    "Ilman lämpötila (degC)": -2.1,
    "Ylin lämpötila (degC)": 0.3,
    "Alin lämpötila (degC)": -3.2
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 21,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.6,
    "Lumensyvyys (cm)": 3,
    "Ilman lämpötila (degC)": -5,
    "Ylin lämpötila (degC)": -1.5,
    "Alin lämpötila (degC)": -7.6
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 22,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 1.6,
    "Lumensyvyys (cm)": 3,
    "Ilman lämpötila (degC)": -8.1,
    "Ylin lämpötila (degC)": -7.2,
    "Alin lämpötila (degC)": -9.8
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 23,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 6,
    "Ilman lämpötila (degC)": -8.1,
    "Ylin lämpötila (degC)": -7.1,
    "Alin lämpötila (degC)": -8.7
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 24,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.3,
    "Lumensyvyys (cm)": 5,
    "Ilman lämpötila (degC)": -9.6,
    "Ylin lämpötila (degC)": -8.6,
    "Alin lämpötila (degC)": -11.9
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 25,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.6,
    "Lumensyvyys (cm)": 5,
    "Ilman lämpötila (degC)": 0.7,
    "Ylin lämpötila (degC)": 2,
    "Alin lämpötila (degC)": -10.5
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 26,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 3,
    "Ilman lämpötila (degC)": 1.1,
    "Ylin lämpötila (degC)": 3.2,
    "Alin lämpötila (degC)": -0.9
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 27,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.9,
    "Lumensyvyys (cm)": 3,
    "Ilman lämpötila (degC)": 0.2,
    "Ylin lämpötila (degC)": 2.3,
    "Alin lämpötila (degC)": -1.3
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 28,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 2,
    "Ilman lämpötila (degC)": -0.6,
    "Ylin lämpötila (degC)": 0.8,
    "Alin lämpötila (degC)": -1.3
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 29,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 2,
    "Ilman lämpötila (degC)": 0.7,
    "Ylin lämpötila (degC)": 3.2,
    "Alin lämpötila (degC)": -2
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 30,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 0,
    "Ilman lämpötila (degC)": 0.2,
    "Ylin lämpötila (degC)": 1.4,
    "Alin lämpötila (degC)": -0.7
  },
  {
    "Vuosi": 2018,
    "Kk": 12,
    "Pv": 31,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 3.2,
    "Lumensyvyys (cm)": 2,
    "Ilman lämpötila (degC)": -0.5,
    "Ylin lämpötila (degC)": 0.7,
    "Alin lämpötila (degC)": -1.9
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 1,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 1.5,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 2.7,
    "Ylin lämpötila (degC)": 4.5,
    "Alin lämpötila (degC)": 0.5
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 2,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.2,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": -2.9,
    "Ylin lämpötila (degC)": 2.2,
    "Alin lämpötila (degC)": -6.1
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 3,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 1.8,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": -9.1,
    "Ylin lämpötila (degC)": -6.1,
    "Alin lämpötila (degC)": -11.1
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 4,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.5,
    "Lumensyvyys (cm)": 0,
    "Ilman lämpötila (degC)": -1.2,
    "Ylin lämpötila (degC)": 1.2,
    "Alin lämpötila (degC)": -12.1
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 5,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 2,
    "Ilman lämpötila (degC)": -4.7,
    "Ylin lämpötila (degC)": -0.3,
    "Alin lämpötila (degC)": -5.4
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 6,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.8,
    "Lumensyvyys (cm)": 2,
    "Ilman lämpötila (degC)": -3.5,
    "Ylin lämpötila (degC)": 0.5,
    "Alin lämpötila (degC)": -7.6
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 7,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 3.5,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 1.3,
    "Ylin lämpötila (degC)": 2.6,
    "Alin lämpötila (degC)": -0.2
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 8,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 12.2,
    "Lumensyvyys (cm)": 0,
    "Ilman lämpötila (degC)": 0.4,
    "Ylin lämpötila (degC)": 1.8,
    "Alin lämpötila (degC)": -0.9
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 9,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.8,
    "Lumensyvyys (cm)": 14,
    "Ilman lämpötila (degC)": -1.9,
    "Ylin lämpötila (degC)": 0,
    "Alin lämpötila (degC)": -4.1
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 10,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.5,
    "Lumensyvyys (cm)": 13,
    "Ilman lämpötila (degC)": -4.1,
    "Ylin lämpötila (degC)": -3.1,
    "Alin lämpötila (degC)": -6.1
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 11,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 11,
    "Ilman lämpötila (degC)": 1.4,
    "Ylin lämpötila (degC)": 2.1,
    "Alin lämpötila (degC)": -3.8
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 12,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 8,
    "Ilman lämpötila (degC)": -1.3,
    "Ylin lämpötila (degC)": 2,
    "Alin lämpötila (degC)": -3.6
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 13,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 5.5,
    "Lumensyvyys (cm)": 8,
    "Ilman lämpötila (degC)": -2.2,
    "Ylin lämpötila (degC)": 1.1,
    "Alin lämpötila (degC)": -6.3
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 14,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 1.1,
    "Lumensyvyys (cm)": 11,
    "Ilman lämpötila (degC)": -2,
    "Ylin lämpötila (degC)": 0.7,
    "Alin lämpötila (degC)": -4.8
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 15,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.6,
    "Lumensyvyys (cm)": 12,
    "Ilman lämpötila (degC)": -6.1,
    "Ylin lämpötila (degC)": -4.4,
    "Alin lämpötila (degC)": -9.6
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 16,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 11.2,
    "Lumensyvyys (cm)": 14,
    "Ilman lämpötila (degC)": -5.3,
    "Ylin lämpötila (degC)": -3.4,
    "Alin lämpötila (degC)": -8.7
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 17,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.8,
    "Lumensyvyys (cm)": 24,
    "Ilman lämpötila (degC)": -4.5,
    "Ylin lämpötila (degC)": -1.2,
    "Alin lämpötila (degC)": -7.5
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 18,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 23,
    "Ilman lämpötila (degC)": -9.2,
    "Ylin lämpötila (degC)": -6.1,
    "Alin lämpötila (degC)": -11.4
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 19,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 2.2,
    "Lumensyvyys (cm)": 22,
    "Ilman lämpötila (degC)": -5.2,
    "Ylin lämpötila (degC)": 0.6,
    "Alin lämpötila (degC)": -13
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 20,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 23,
    "Ilman lämpötila (degC)": -7.9,
    "Ylin lämpötila (degC)": -0.4,
    "Alin lämpötila (degC)": -11.7
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 21,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 21,
    "Ilman lämpötila (degC)": -15.1,
    "Ylin lämpötila (degC)": -11.4,
    "Alin lämpötila (degC)": -17.3
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 22,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.3,
    "Lumensyvyys (cm)": 21,
    "Ilman lämpötila (degC)": -13.8,
    "Ylin lämpötila (degC)": -5.3,
    "Alin lämpötila (degC)": -20.3
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 23,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 1.8,
    "Lumensyvyys (cm)": 21,
    "Ilman lämpötila (degC)": -1.7,
    "Ylin lämpötila (degC)": 0.1,
    "Alin lämpötila (degC)": -5.6
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 24,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 22,
    "Ilman lämpötila (degC)": -7.8,
    "Ylin lämpötila (degC)": -1.2,
    "Alin lämpötila (degC)": -10.7
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 25,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 2.1,
    "Lumensyvyys (cm)": 21,
    "Ilman lämpötila (degC)": -3.6,
    "Ylin lämpötila (degC)": -2.1,
    "Alin lämpötila (degC)": -10.1
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 26,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 2.5,
    "Lumensyvyys (cm)": 23,
    "Ilman lämpötila (degC)": -8.2,
    "Ylin lämpötila (degC)": -4.7,
    "Alin lämpötila (degC)": -9.9
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 27,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 29,
    "Ilman lämpötila (degC)": -13.8,
    "Ylin lämpötila (degC)": -9.8,
    "Alin lämpötila (degC)": -16
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 28,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 12.3,
    "Lumensyvyys (cm)": 27,
    "Ilman lämpötila (degC)": -7.3,
    "Ylin lämpötila (degC)": -5.1,
    "Alin lämpötila (degC)": -15.9
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 29,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 8.6,
    "Lumensyvyys (cm)": 36,
    "Ilman lämpötila (degC)": -4.5,
    "Ylin lämpötila (degC)": -3.8,
    "Alin lämpötila (degC)": -5.6
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 30,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 1.2,
    "Lumensyvyys (cm)": 42,
    "Ilman lämpötila (degC)": -0.8,
    "Ylin lämpötila (degC)": 0.8,
    "Alin lämpötila (degC)": -4.7
  },
  {
    "Vuosi": 2019,
    "Kk": 1,
    "Pv": 31,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 40,
    "Ilman lämpötila (degC)": -0.8,
    "Ylin lämpötila (degC)": 0.7,
    "Alin lämpötila (degC)": -3.4
  },
  {
    "Vuosi": 2019,
    "Kk": 2,
    "Pv": 1,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.8,
    "Lumensyvyys (cm)": 39,
    "Ilman lämpötila (degC)": -3.6,
    "Ylin lämpötila (degC)": -1.3,
    "Alin lämpötila (degC)": -5.8
  },
  {
    "Vuosi": 2019,
    "Kk": 2,
    "Pv": 2,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 8.1,
    "Lumensyvyys (cm)": 37,
    "Ilman lämpötila (degC)": -2.6,
    "Ylin lämpötila (degC)": -1.9,
    "Alin lämpötila (degC)": -4.4
  },
  {
    "Vuosi": 2019,
    "Kk": 2,
    "Pv": 3,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 5.7,
    "Lumensyvyys (cm)": 42,
    "Ilman lämpötila (degC)": -0.6,
    "Ylin lämpötila (degC)": 2,
    "Alin lämpötila (degC)": -3.3
  },
  {
    "Vuosi": 2019,
    "Kk": 2,
    "Pv": 4,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 1.6,
    "Lumensyvyys (cm)": 39,
    "Ilman lämpötila (degC)": -3.5,
    "Ylin lämpötila (degC)": 1.2,
    "Alin lämpötila (degC)": -5.8
  },
  {
    "Vuosi": 2019,
    "Kk": 2,
    "Pv": 5,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 5.2,
    "Lumensyvyys (cm)": 39,
    "Ilman lämpötila (degC)": 0,
    "Ylin lämpötila (degC)": 1.2,
    "Alin lämpötila (degC)": -5.7
  },
  {
    "Vuosi": 2019,
    "Kk": 2,
    "Pv": 6,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 2.2,
    "Lumensyvyys (cm)": 44,
    "Ilman lämpötila (degC)": -3.7,
    "Ylin lämpötila (degC)": -0.2,
    "Alin lämpötila (degC)": -7.8
  },
  {
    "Vuosi": 2019,
    "Kk": 2,
    "Pv": 7,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 1.1,
    "Lumensyvyys (cm)": 46,
    "Ilman lämpötila (degC)": 0.1,
    "Ylin lämpötila (degC)": 1.7,
    "Alin lämpötila (degC)": -6
  },
  {
    "Vuosi": 2019,
    "Kk": 2,
    "Pv": 8,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.5,
    "Lumensyvyys (cm)": 43,
    "Ilman lämpötila (degC)": 1.5,
    "Ylin lämpötila (degC)": 2.4,
    "Alin lämpötila (degC)": 0.7
  },
  {
    "Vuosi": 2019,
    "Kk": 2,
    "Pv": 9,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 5.9,
    "Lumensyvyys (cm)": 34,
    "Ilman lämpötila (degC)": 2,
    "Ylin lämpötila (degC)": 2.7,
    "Alin lämpötila (degC)": 1.6
  },
  {
    "Vuosi": 2019,
    "Kk": 2,
    "Pv": 10,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 2.5,
    "Lumensyvyys (cm)": 31,
    "Ilman lämpötila (degC)": 2.2,
    "Ylin lämpötila (degC)": 3.1,
    "Alin lämpötila (degC)": 0.5
  },
  {
    "Vuosi": 2019,
    "Kk": 2,
    "Pv": 11,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 7.3,
    "Lumensyvyys (cm)": 28,
    "Ilman lämpötila (degC)": 1.3,
    "Ylin lämpötila (degC)": 2.8,
    "Alin lämpötila (degC)": 0.4
  },
  {
    "Vuosi": 2019,
    "Kk": 2,
    "Pv": 12,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 27,
    "Ilman lämpötila (degC)": -1.1,
    "Ylin lämpötila (degC)": 0.7,
    "Alin lämpötila (degC)": -2.3
  },
  {
    "Vuosi": 2019,
    "Kk": 2,
    "Pv": 13,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 1.9,
    "Lumensyvyys (cm)": 27,
    "Ilman lämpötila (degC)": -0.1,
    "Ylin lämpötila (degC)": 1.1,
    "Alin lämpötila (degC)": -3.7
  },
  {
    "Vuosi": 2019,
    "Kk": 2,
    "Pv": 14,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 28,
    "Ilman lämpötila (degC)": 2.3,
    "Ylin lämpötila (degC)": 2.9,
    "Alin lämpötila (degC)": 0.7
  },
  {
    "Vuosi": 2019,
    "Kk": 2,
    "Pv": 15,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 26,
    "Ilman lämpötila (degC)": 5,
    "Ylin lämpötila (degC)": 7.7,
    "Alin lämpötila (degC)": 1.9
  },
  {
    "Vuosi": 2019,
    "Kk": 2,
    "Pv": 16,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 25,
    "Ilman lämpötila (degC)": 3,
    "Ylin lämpötila (degC)": 6.9,
    "Alin lämpötila (degC)": 0.9
  },
  {
    "Vuosi": 2019,
    "Kk": 2,
    "Pv": 17,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 22,
    "Ilman lämpötila (degC)": 1.2,
    "Ylin lämpötila (degC)": 4,
    "Alin lämpötila (degC)": -0.9
  },
  {
    "Vuosi": 2019,
    "Kk": 2,
    "Pv": 18,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 22,
    "Ilman lämpötila (degC)": 0.7,
    "Ylin lämpötila (degC)": 2.5,
    "Alin lämpötila (degC)": -2.7
  },
  {
    "Vuosi": 2019,
    "Kk": 2,
    "Pv": 19,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 3.7,
    "Lumensyvyys (cm)": 19,
    "Ilman lämpötila (degC)": 2.1,
    "Ylin lämpötila (degC)": 2.2,
    "Alin lämpötila (degC)": 1.6
  },
  {
    "Vuosi": 2019,
    "Kk": 2,
    "Pv": 20,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.1,
    "Lumensyvyys (cm)": 17,
    "Ilman lämpötila (degC)": -0.6,
    "Ylin lämpötila (degC)": 2.8,
    "Alin lämpötila (degC)": -3.8
  },
  {
    "Vuosi": 2019,
    "Kk": 2,
    "Pv": 21,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 16,
    "Ilman lämpötila (degC)": -6.4,
    "Ylin lämpötila (degC)": -3.8,
    "Alin lämpötila (degC)": -8.3
  },
  {
    "Vuosi": 2019,
    "Kk": 2,
    "Pv": 22,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 1.6,
    "Lumensyvyys (cm)": 16,
    "Ilman lämpötila (degC)": -6.2,
    "Ylin lämpötila (degC)": -2.2,
    "Alin lämpötila (degC)": -10.8
  },
  {
    "Vuosi": 2019,
    "Kk": 2,
    "Pv": 23,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 16,
    "Ilman lämpötila (degC)": 1.8,
    "Ylin lämpötila (degC)": 5.2,
    "Alin lämpötila (degC)": -4.5
  },
  {
    "Vuosi": 2019,
    "Kk": 2,
    "Pv": 24,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 16,
    "Ilman lämpötila (degC)": 2.7,
    "Ylin lämpötila (degC)": 4.5,
    "Alin lämpötila (degC)": 0.9
  },
  {
    "Vuosi": 2019,
    "Kk": 2,
    "Pv": 25,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.9,
    "Lumensyvyys (cm)": 14,
    "Ilman lämpötila (degC)": 5.2,
    "Ylin lämpötila (degC)": 7.8,
    "Alin lämpötila (degC)": 4.2
  },
  {
    "Vuosi": 2019,
    "Kk": 2,
    "Pv": 26,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 13,
    "Ilman lämpötila (degC)": 2.1,
    "Ylin lämpötila (degC)": 4.8,
    "Alin lämpötila (degC)": 1.1
  },
  {
    "Vuosi": 2019,
    "Kk": 2,
    "Pv": 27,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 12,
    "Ilman lämpötila (degC)": 3.5,
    "Ylin lämpötila (degC)": 5.7,
    "Alin lämpötila (degC)": -0.5
  },
  {
    "Vuosi": 2019,
    "Kk": 2,
    "Pv": 28,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.5,
    "Lumensyvyys (cm)": 11,
    "Ilman lämpötila (degC)": 2,
    "Ylin lämpötila (degC)": 5.1,
    "Alin lämpötila (degC)": -1.2
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 1,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 10,
    "Ilman lämpötila (degC)": -4.9,
    "Ylin lämpötila (degC)": -1.1,
    "Alin lämpötila (degC)": -7.6
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 2,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 10,
    "Ilman lämpötila (degC)": 0.5,
    "Ylin lämpötila (degC)": 3.1,
    "Alin lämpötila (degC)": -5.2
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 3,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 10,
    "Ilman lämpötila (degC)": -4.9,
    "Ylin lämpötila (degC)": 1.5,
    "Alin lämpötila (degC)": -7.9
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 4,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 3.8,
    "Lumensyvyys (cm)": 9,
    "Ilman lämpötila (degC)": -2.7,
    "Ylin lämpötila (degC)": -1.3,
    "Alin lämpötila (degC)": -4.9
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 5,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 14,
    "Ilman lämpötila (degC)": -4.6,
    "Ylin lämpötila (degC)": -1.3,
    "Alin lämpötila (degC)": -7.4
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 6,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.2,
    "Lumensyvyys (cm)": 13,
    "Ilman lämpötila (degC)": -6.9,
    "Ylin lämpötila (degC)": -2.7,
    "Alin lämpötila (degC)": -14.3
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 7,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 8.7,
    "Lumensyvyys (cm)": 12,
    "Ilman lämpötila (degC)": 0.2,
    "Ylin lämpötila (degC)": 0.7,
    "Alin lämpötila (degC)": -2.8
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 8,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 5.1,
    "Lumensyvyys (cm)": 13,
    "Ilman lämpötila (degC)": 3,
    "Ylin lämpötila (degC)": 4.7,
    "Alin lämpötila (degC)": 0.6
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 9,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 3.7,
    "Lumensyvyys (cm)": 9,
    "Ilman lämpötila (degC)": 0.4,
    "Ylin lämpötila (degC)": 3.3,
    "Alin lämpötila (degC)": -1.9
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 10,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 10,
    "Ilman lämpötila (degC)": -0.8,
    "Ylin lämpötila (degC)": 2.1,
    "Alin lämpötila (degC)": -2.2
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 11,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.1,
    "Lumensyvyys (cm)": 10,
    "Ilman lämpötila (degC)": -4.9,
    "Ylin lämpötila (degC)": -2.2,
    "Alin lämpötila (degC)": -6.7
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 12,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": 10,
    "Ilman lämpötila (degC)": -4.8,
    "Ylin lämpötila (degC)": -1.3,
    "Alin lämpötila (degC)": -8.6
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 13,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 4.2,
    "Lumensyvyys (cm)": 10,
    "Ilman lämpötila (degC)": -3.3,
    "Ylin lämpötila (degC)": -0.1,
    "Alin lämpötila (degC)": -9.1
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 14,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.4,
    "Lumensyvyys (cm)": 14,
    "Ilman lämpötila (degC)": 1.4,
    "Ylin lämpötila (degC)": 2.6,
    "Alin lämpötila (degC)": -1.1
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 15,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 3.7,
    "Lumensyvyys (cm)": 10,
    "Ilman lämpötila (degC)": 2.1,
    "Ylin lämpötila (degC)": 2.5,
    "Alin lämpötila (degC)": 1.5
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 16,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 1.7,
    "Lumensyvyys (cm)": 8,
    "Ilman lämpötila (degC)": 1.8,
    "Ylin lämpötila (degC)": 3.1,
    "Alin lämpötila (degC)": 1.1
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 17,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 8.1,
    "Lumensyvyys (cm)": 7,
    "Ilman lämpötila (degC)": 1.7,
    "Ylin lämpötila (degC)": 2.5,
    "Alin lämpötila (degC)": 0.6
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 18,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 1,
    "Lumensyvyys (cm)": 5,
    "Ilman lämpötila (degC)": 3.3,
    "Ylin lämpötila (degC)": 4.1,
    "Alin lämpötila (degC)": 1.7
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 19,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.2,
    "Lumensyvyys (cm)": 2,
    "Ilman lämpötila (degC)": 2.6,
    "Ylin lämpötila (degC)": 4.9,
    "Alin lämpötila (degC)": 2
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 20,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.7,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 1.3,
    "Ylin lämpötila (degC)": 3.3,
    "Alin lämpötila (degC)": -0.4
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 21,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 2.9,
    "Ylin lämpötila (degC)": 5.3,
    "Alin lämpötila (degC)": 0.9
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 22,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 3.9,
    "Ylin lämpötila (degC)": 7.4,
    "Alin lämpötila (degC)": 1.2
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 23,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.5,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 2.3,
    "Ylin lämpötila (degC)": 3.6,
    "Alin lämpötila (degC)": 1.2
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 24,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 4,
    "Ylin lämpötila (degC)": 6.8,
    "Alin lämpötila (degC)": 1.5
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 25,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.2,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 1.5,
    "Ylin lämpötila (degC)": 5.3,
    "Alin lämpötila (degC)": -0.7
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 26,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 0.3,
    "Ylin lämpötila (degC)": 3.5,
    "Alin lämpötila (degC)": -2.9
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 27,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 0.2,
    "Ylin lämpötila (degC)": 3.1,
    "Alin lämpötila (degC)": -4.1
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 28,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 3.6,
    "Ylin lämpötila (degC)": 7.4,
    "Alin lämpötila (degC)": -0.9
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 29,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 6.1,
    "Ylin lämpötila (degC)": 11.5,
    "Alin lämpötila (degC)": 2.6
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 30,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 1.2,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 5.3,
    "Ylin lämpötila (degC)": 10,
    "Alin lämpötila (degC)": 2.8
  },
  {
    "Vuosi": 2019,
    "Kk": 3,
    "Pv": 31,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 3.3,
    "Ylin lämpötila (degC)": 5.6,
    "Alin lämpötila (degC)": 2.3
  },
  {
    "Vuosi": 2019,
    "Kk": 4,
    "Pv": 1,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 3.5,
    "Ylin lämpötila (degC)": 7.8,
    "Alin lämpötila (degC)": -0.1
  },
  {
    "Vuosi": 2019,
    "Kk": 4,
    "Pv": 2,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 3.4,
    "Ylin lämpötila (degC)": 6,
    "Alin lämpötila (degC)": 1
  },
  {
    "Vuosi": 2019,
    "Kk": 4,
    "Pv": 3,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 6,
    "Ylin lämpötila (degC)": 10.8,
    "Alin lämpötila (degC)": 2.1
  },
  {
    "Vuosi": 2019,
    "Kk": 4,
    "Pv": 4,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 6.6,
    "Ylin lämpötila (degC)": 12.5,
    "Alin lämpötila (degC)": 3.5
  },
  {
    "Vuosi": 2019,
    "Kk": 4,
    "Pv": 5,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 5.8,
    "Ylin lämpötila (degC)": 11.6,
    "Alin lämpötila (degC)": -0.1
  },
  {
    "Vuosi": 2019,
    "Kk": 4,
    "Pv": 6,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 6.6,
    "Ylin lämpötila (degC)": 10.9,
    "Alin lämpötila (degC)": 2.1
  },
  {
    "Vuosi": 2019,
    "Kk": 4,
    "Pv": 7,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 6.4,
    "Ylin lämpötila (degC)": 10.3,
    "Alin lämpötila (degC)": 1
  },
  {
    "Vuosi": 2019,
    "Kk": 4,
    "Pv": 8,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 3.4,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 2.3,
    "Ylin lämpötila (degC)": 9.5,
    "Alin lämpötila (degC)": 1.3
  },
  {
    "Vuosi": 2019,
    "Kk": 4,
    "Pv": 9,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 2.1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 2.2,
    "Ylin lämpötila (degC)": 5.1,
    "Alin lämpötila (degC)": 0.9
  },
  {
    "Vuosi": 2019,
    "Kk": 4,
    "Pv": 10,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": -0.4,
    "Ylin lämpötila (degC)": 2.5,
    "Alin lämpötila (degC)": -1.2
  },
  {
    "Vuosi": 2019,
    "Kk": 4,
    "Pv": 11,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": -0.3,
    "Ylin lämpötila (degC)": 4.3,
    "Alin lämpötila (degC)": -3.1
  },
  {
    "Vuosi": 2019,
    "Kk": 4,
    "Pv": 12,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 1.5,
    "Ylin lämpötila (degC)": 5,
    "Alin lämpötila (degC)": -3.6
  },
  {
    "Vuosi": 2019,
    "Kk": 4,
    "Pv": 13,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 4.5,
    "Ylin lämpötila (degC)": 6.4,
    "Alin lämpötila (degC)": 2
  },
  {
    "Vuosi": 2019,
    "Kk": 4,
    "Pv": 14,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 4.9,
    "Ylin lämpötila (degC)": 8.9,
    "Alin lämpötila (degC)": 3.2
  },
  {
    "Vuosi": 2019,
    "Kk": 4,
    "Pv": 15,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 4.7,
    "Ylin lämpötila (degC)": 9.1,
    "Alin lämpötila (degC)": -0.7
  },
  {
    "Vuosi": 2019,
    "Kk": 4,
    "Pv": 16,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 7.1,
    "Ylin lämpötila (degC)": 13.1,
    "Alin lämpötila (degC)": 1.1
  },
  {
    "Vuosi": 2019,
    "Kk": 4,
    "Pv": 17,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 7,
    "Ylin lämpötila (degC)": 11.1,
    "Alin lämpötila (degC)": 1.1
  },
  {
    "Vuosi": 2019,
    "Kk": 4,
    "Pv": 18,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 9.2,
    "Ylin lämpötila (degC)": 15.8,
    "Alin lämpötila (degC)": 3.9
  },
  {
    "Vuosi": 2019,
    "Kk": 4,
    "Pv": 19,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 12,
    "Ylin lämpötila (degC)": 17.1,
    "Alin lämpötila (degC)": 4.3
  },
  {
    "Vuosi": 2019,
    "Kk": 4,
    "Pv": 20,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 9.4,
    "Ylin lämpötila (degC)": 13.8,
    "Alin lämpötila (degC)": 5.4
  },
  {
    "Vuosi": 2019,
    "Kk": 4,
    "Pv": 21,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 6.4,
    "Ylin lämpötila (degC)": 9.2,
    "Alin lämpötila (degC)": 3.8
  },
  {
    "Vuosi": 2019,
    "Kk": 4,
    "Pv": 22,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 9.8,
    "Ylin lämpötila (degC)": 14.9,
    "Alin lämpötila (degC)": 4.5
  },
  {
    "Vuosi": 2019,
    "Kk": 4,
    "Pv": 23,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 12.3,
    "Ylin lämpötila (degC)": 18.6,
    "Alin lämpötila (degC)": 6.1
  },
  {
    "Vuosi": 2019,
    "Kk": 4,
    "Pv": 24,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 11.9,
    "Ylin lämpötila (degC)": 16.8,
    "Alin lämpötila (degC)": 4.8
  },
  {
    "Vuosi": 2019,
    "Kk": 4,
    "Pv": 25,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 13.7,
    "Ylin lämpötila (degC)": 17.5,
    "Alin lämpötila (degC)": 8.4
  },
  {
    "Vuosi": 2019,
    "Kk": 4,
    "Pv": 26,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.6,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 12.2,
    "Ylin lämpötila (degC)": 15.3,
    "Alin lämpötila (degC)": 10.1
  },
  {
    "Vuosi": 2019,
    "Kk": 4,
    "Pv": 27,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 14.3,
    "Ylin lämpötila (degC)": 18.7,
    "Alin lämpötila (degC)": 8.5
  },
  {
    "Vuosi": 2019,
    "Kk": 4,
    "Pv": 28,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 6.1,
    "Ylin lämpötila (degC)": 13.9,
    "Alin lämpötila (degC)": 4.5
  },
  {
    "Vuosi": 2019,
    "Kk": 4,
    "Pv": 29,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 5.6,
    "Ylin lämpötila (degC)": 9.3,
    "Alin lämpötila (degC)": 1.3
  },
  {
    "Vuosi": 2019,
    "Kk": 4,
    "Pv": 30,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 6.7,
    "Ylin lämpötila (degC)": 10.1,
    "Alin lämpötila (degC)": 3.1
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 1,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 4.2,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 8.3,
    "Ylin lämpötila (degC)": 14.4,
    "Alin lämpötila (degC)": 3.4
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 2,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 13.2,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 4.4,
    "Ylin lämpötila (degC)": 7.9,
    "Alin lämpötila (degC)": 2.7
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 3,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 2,
    "Ylin lämpötila (degC)": 5.2,
    "Alin lämpötila (degC)": 0.3
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 4,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 6.1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 2.1,
    "Ylin lämpötila (degC)": 5.8,
    "Alin lämpötila (degC)": -0.4
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 5,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 4.8,
    "Ylin lämpötila (degC)": 8.5,
    "Alin lämpötila (degC)": -0.2
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 6,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 6.7,
    "Ylin lämpötila (degC)": 10,
    "Alin lämpötila (degC)": 3.7
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 7,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 7,
    "Ylin lämpötila (degC)": 9.5,
    "Alin lämpötila (degC)": 5.2
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 8,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 7.3,
    "Ylin lämpötila (degC)": 11.3,
    "Alin lämpötila (degC)": 4.7
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 9,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 9.4,
    "Ylin lämpötila (degC)": 13.2,
    "Alin lämpötila (degC)": 3.8
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 10,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 3.6,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 8.4,
    "Ylin lämpötila (degC)": 11.6,
    "Alin lämpötila (degC)": 7.7
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 11,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 8.3,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 9.5,
    "Ylin lämpötila (degC)": 12,
    "Alin lämpötila (degC)": 7.4
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 12,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 8.8,
    "Ylin lämpötila (degC)": 12.6,
    "Alin lämpötila (degC)": 5.7
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 13,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 8.6,
    "Ylin lämpötila (degC)": 12.3,
    "Alin lämpötila (degC)": 4.9
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 14,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 9,
    "Ylin lämpötila (degC)": 14,
    "Alin lämpötila (degC)": 6.6
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 15,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 10.1,
    "Ylin lämpötila (degC)": 13.6,
    "Alin lämpötila (degC)": 5.1
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 16,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 11.8,
    "Ylin lämpötila (degC)": 16,
    "Alin lämpötila (degC)": 4.9
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 17,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 13.8,
    "Ylin lämpötila (degC)": 18.2,
    "Alin lämpötila (degC)": 6.7
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 18,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 15.6,
    "Ylin lämpötila (degC)": 20.2,
    "Alin lämpötila (degC)": 8.9
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 19,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 17.1,
    "Ylin lämpötila (degC)": 21,
    "Alin lämpötila (degC)": 12.2
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 20,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.8,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 17.3,
    "Ylin lämpötila (degC)": 20.5,
    "Alin lämpötila (degC)": 13.9
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 21,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 18.3,
    "Ylin lämpötila (degC)": 24.5,
    "Alin lämpötila (degC)": 14.8
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 22,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.2,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 17.8,
    "Ylin lämpötila (degC)": 21.6,
    "Alin lämpötila (degC)": 15.5
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 23,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.5,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 12.6,
    "Ylin lämpötila (degC)": 17.8,
    "Alin lämpötila (degC)": 9.6
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 24,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 1.8,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 9.3,
    "Ylin lämpötila (degC)": 10.5,
    "Alin lämpötila (degC)": 8.2
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 25,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.9,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 10.9,
    "Ylin lämpötila (degC)": 13.4,
    "Alin lämpötila (degC)": 8.3
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 26,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 14.8,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 9.5,
    "Ylin lämpötila (degC)": 11.8,
    "Alin lämpötila (degC)": 8.1
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 27,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.4,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 10.5,
    "Ylin lämpötila (degC)": 12.9,
    "Alin lämpötila (degC)": 8.9
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 28,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 3.9,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 11.7,
    "Ylin lämpötila (degC)": 15.2,
    "Alin lämpötila (degC)": 9
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 29,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 12.4,
    "Ylin lämpötila (degC)": 16,
    "Alin lämpötila (degC)": 10.8
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 30,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 3.2,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 12.5,
    "Ylin lämpötila (degC)": 16.4,
    "Alin lämpötila (degC)": 6.1
  },
  {
    "Vuosi": 2019,
    "Kk": 5,
    "Pv": 31,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 12.1,
    "Ylin lämpötila (degC)": 15.3,
    "Alin lämpötila (degC)": 8.7
  },
  {
    "Vuosi": 2019,
    "Kk": 6,
    "Pv": 1,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 2.3,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 12.3,
    "Ylin lämpötila (degC)": 16.5,
    "Alin lämpötila (degC)": 8.4
  },
  {
    "Vuosi": 2019,
    "Kk": 6,
    "Pv": 2,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 13.4,
    "Ylin lämpötila (degC)": 17.8,
    "Alin lämpötila (degC)": 10.1
  },
  {
    "Vuosi": 2019,
    "Kk": 6,
    "Pv": 3,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 5.6,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 13,
    "Ylin lämpötila (degC)": 16.7,
    "Alin lämpötila (degC)": 7.1
  },
  {
    "Vuosi": 2019,
    "Kk": 6,
    "Pv": 4,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 17.2,
    "Ylin lämpötila (degC)": 23.6,
    "Alin lämpötila (degC)": 12.7
  },
  {
    "Vuosi": 2019,
    "Kk": 6,
    "Pv": 5,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 18.7,
    "Ylin lämpötila (degC)": 23.1,
    "Alin lämpötila (degC)": 12.7
  },
  {
    "Vuosi": 2019,
    "Kk": 6,
    "Pv": 6,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 21.6,
    "Ylin lämpötila (degC)": 26.9,
    "Alin lämpötila (degC)": 14.9
  },
  {
    "Vuosi": 2019,
    "Kk": 6,
    "Pv": 7,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 21.9,
    "Ylin lämpötila (degC)": 26.8,
    "Alin lämpötila (degC)": 18.2
  },
  {
    "Vuosi": 2019,
    "Kk": 6,
    "Pv": 8,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 2.5,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 22.1,
    "Ylin lämpötila (degC)": 26.5,
    "Alin lämpötila (degC)": 17.3
  },
  {
    "Vuosi": 2019,
    "Kk": 6,
    "Pv": 9,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 18.3,
    "Ylin lämpötila (degC)": 22.2,
    "Alin lämpötila (degC)": 16.2
  },
  {
    "Vuosi": 2019,
    "Kk": 6,
    "Pv": 10,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 16.4,
    "Ylin lämpötila (degC)": 19.5,
    "Alin lämpötila (degC)": 13.7
  },
  {
    "Vuosi": 2019,
    "Kk": 6,
    "Pv": 11,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 17,
    "Ylin lämpötila (degC)": 21.7,
    "Alin lämpötila (degC)": 12.2
  },
  {
    "Vuosi": 2019,
    "Kk": 6,
    "Pv": 12,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 15,
    "Ylin lämpötila (degC)": 18.7,
    "Alin lämpötila (degC)": 12.6
  },
  {
    "Vuosi": 2019,
    "Kk": 6,
    "Pv": 13,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 1.1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 14,
    "Ylin lämpötila (degC)": 16,
    "Alin lämpötila (degC)": 12.2
  },
  {
    "Vuosi": 2019,
    "Kk": 6,
    "Pv": 14,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 14.4,
    "Ylin lämpötila (degC)": 16.5,
    "Alin lämpötila (degC)": 12.6
  },
  {
    "Vuosi": 2019,
    "Kk": 6,
    "Pv": 15,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 16.9,
    "Ylin lämpötila (degC)": 21.6,
    "Alin lämpötila (degC)": 13.5
  },
  {
    "Vuosi": 2019,
    "Kk": 6,
    "Pv": 16,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 18.4,
    "Ylin lämpötila (degC)": 23.3,
    "Alin lämpötila (degC)": 12.5
  },
  {
    "Vuosi": 2019,
    "Kk": 6,
    "Pv": 17,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 18.5,
    "Ylin lämpötila (degC)": 22.4,
    "Alin lämpötila (degC)": 13.6
  },
  {
    "Vuosi": 2019,
    "Kk": 6,
    "Pv": 18,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 18.2,
    "Ylin lämpötila (degC)": 22.8,
    "Alin lämpötila (degC)": 15
  },
  {
    "Vuosi": 2019,
    "Kk": 6,
    "Pv": 19,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 18.8,
    "Ylin lämpötila (degC)": 22.6,
    "Alin lämpötila (degC)": 14.1
  },
  {
    "Vuosi": 2019,
    "Kk": 6,
    "Pv": 20,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 20,
    "Ylin lämpötila (degC)": 24.6,
    "Alin lämpötila (degC)": 15
  },
  {
    "Vuosi": 2019,
    "Kk": 6,
    "Pv": 21,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 20,
    "Ylin lämpötila (degC)": 24.5,
    "Alin lämpötila (degC)": 17.2
  },
  {
    "Vuosi": 2019,
    "Kk": 6,
    "Pv": 22,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.7,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 17.3,
    "Ylin lämpötila (degC)": 20,
    "Alin lämpötila (degC)": 14.2
  },
  {
    "Vuosi": 2019,
    "Kk": 6,
    "Pv": 23,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 17.3,
    "Ylin lämpötila (degC)": 20.2,
    "Alin lämpötila (degC)": 13.6
  },
  {
    "Vuosi": 2019,
    "Kk": 6,
    "Pv": 24,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 19.5,
    "Ylin lämpötila (degC)": 23.8,
    "Alin lämpötila (degC)": 13.9
  },
  {
    "Vuosi": 2019,
    "Kk": 6,
    "Pv": 25,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.7,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 17,
    "Ylin lämpötila (degC)": 20.8,
    "Alin lämpötila (degC)": 11.6
  },
  {
    "Vuosi": 2019,
    "Kk": 6,
    "Pv": 26,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 2,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 15.1,
    "Ylin lämpötila (degC)": 19.5,
    "Alin lämpötila (degC)": 13.5
  },
  {
    "Vuosi": 2019,
    "Kk": 6,
    "Pv": 27,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.7,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 15.8,
    "Ylin lämpötila (degC)": 20.1,
    "Alin lämpötila (degC)": 13.6
  },
  {
    "Vuosi": 2019,
    "Kk": 6,
    "Pv": 28,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 16.9,
    "Ylin lämpötila (degC)": 21.5,
    "Alin lämpötila (degC)": 11.5
  },
  {
    "Vuosi": 2019,
    "Kk": 6,
    "Pv": 29,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 15.7,
    "Ylin lämpötila (degC)": 21.3,
    "Alin lämpötila (degC)": 10.9
  },
  {
    "Vuosi": 2019,
    "Kk": 6,
    "Pv": 30,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 17.6,
    "Ylin lämpötila (degC)": 23.2,
    "Alin lämpötila (degC)": 14.4
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 1,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 17.9,
    "Ylin lämpötila (degC)": 23.7,
    "Alin lämpötila (degC)": 15.9
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 2,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 22.5,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 15.5,
    "Ylin lämpötila (degC)": 19.5,
    "Alin lämpötila (degC)": 13.6
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 3,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 15.2,
    "Ylin lämpötila (degC)": 20.6,
    "Alin lämpötila (degC)": 11.9
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 4,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 13.7,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 13.9,
    "Ylin lämpötila (degC)": 17.7,
    "Alin lämpötila (degC)": 10.2
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 5,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 11.7,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 12.9,
    "Ylin lämpötila (degC)": 16.5,
    "Alin lämpötila (degC)": 11
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 6,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 7.4,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 13.3,
    "Ylin lämpötila (degC)": 19.1,
    "Alin lämpötila (degC)": 10.2
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 7,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 2.1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 14.6,
    "Ylin lämpötila (degC)": 18.4,
    "Alin lämpötila (degC)": 10.2
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 8,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 10.3,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 15.2,
    "Ylin lämpötila (degC)": 19.9,
    "Alin lämpötila (degC)": 13
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 9,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 13,
    "Ylin lämpötila (degC)": 15.2,
    "Alin lämpötila (degC)": 11.4
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 10,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 16.8,
    "Ylin lämpötila (degC)": 21.4,
    "Alin lämpötila (degC)": 12.2
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 11,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.2,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 13,
    "Ylin lämpötila (degC)": 19.5,
    "Alin lämpötila (degC)": 11.6
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 12,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 14.4,
    "Ylin lämpötila (degC)": 20,
    "Alin lämpötila (degC)": 8.4
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 13,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 16.5,
    "Ylin lämpötila (degC)": 21.6,
    "Alin lämpötila (degC)": 13.2
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 14,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 15.4,
    "Ylin lämpötila (degC)": 18.1,
    "Alin lämpötila (degC)": 11.4
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 15,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.5,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 16.5,
    "Ylin lämpötila (degC)": 19.2,
    "Alin lämpötila (degC)": 12.8
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 16,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 3.5,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 15.9,
    "Ylin lämpötila (degC)": 20,
    "Alin lämpötila (degC)": 13.9
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 17,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 17.8,
    "Ylin lämpötila (degC)": 22.9,
    "Alin lämpötila (degC)": 13
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 18,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 19.7,
    "Ylin lämpötila (degC)": 24.7,
    "Alin lämpötila (degC)": 12.7
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 19,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 19.8,
    "Ylin lämpötila (degC)": 25,
    "Alin lämpötila (degC)": 14.7
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 20,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 19.7,
    "Ylin lämpötila (degC)": 25.1,
    "Alin lämpötila (degC)": 13.1
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 21,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 20.5,
    "Ylin lämpötila (degC)": 25.1,
    "Alin lämpötila (degC)": 14.2
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 22,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.2,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 20,
    "Ylin lämpötila (degC)": 22.5,
    "Alin lämpötila (degC)": 17.9
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 23,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 21.8,
    "Ylin lämpötila (degC)": 25.7,
    "Alin lämpötila (degC)": 16.3
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 24,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 23.3,
    "Ylin lämpötila (degC)": 28.7,
    "Alin lämpötila (degC)": 16.4
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 25,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 20.9,
    "Ylin lämpötila (degC)": 25.4,
    "Alin lämpötila (degC)": 18.5
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 26,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 22.2,
    "Ylin lämpötila (degC)": 25.6,
    "Alin lämpötila (degC)": 17.4
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 27,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 24.9,
    "Ylin lämpötila (degC)": 29.1,
    "Alin lämpötila (degC)": 19.3
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 28,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 25.3,
    "Ylin lämpötila (degC)": 33.2,
    "Alin lämpötila (degC)": 20.2
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 29,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 17.6,
    "Ylin lämpötila (degC)": 21.6,
    "Alin lämpötila (degC)": 16.6
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 30,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 14.5,
    "Ylin lämpötila (degC)": 18.5,
    "Alin lämpötila (degC)": 11.5
  },
  {
    "Vuosi": 2019,
    "Kk": 7,
    "Pv": 31,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 16,
    "Ylin lämpötila (degC)": 21.2,
    "Alin lämpötila (degC)": 11.4
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 1,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 15.1,
    "Ylin lämpötila (degC)": 19,
    "Alin lämpötila (degC)": 11.7
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 2,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 16.1,
    "Ylin lämpötila (degC)": 21.6,
    "Alin lämpötila (degC)": 11.1
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 3,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 13.8,
    "Ylin lämpötila (degC)": 18.3,
    "Alin lämpötila (degC)": 9.8
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 4,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 13.4,
    "Ylin lämpötila (degC)": 18.3,
    "Alin lämpötila (degC)": 8.8
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 5,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 16.6,
    "Ylin lämpötila (degC)": 23,
    "Alin lämpötila (degC)": 9.4
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 6,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.9,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 16.9,
    "Ylin lämpötila (degC)": 20.3,
    "Alin lämpötila (degC)": 12.6
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 7,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 3,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 17.1,
    "Ylin lämpötila (degC)": 19.9,
    "Alin lämpötila (degC)": 15.1
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 8,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 17.4,
    "Ylin lämpötila (degC)": 20.7,
    "Alin lämpötila (degC)": 14.2
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 9,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 17.4,
    "Ylin lämpötila (degC)": 21.8,
    "Alin lämpötila (degC)": 14.3
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 10,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 18.2,
    "Ylin lämpötila (degC)": 21.9,
    "Alin lämpötila (degC)": 12.4
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 11,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 4.7,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 18,
    "Ylin lämpötila (degC)": 19.7,
    "Alin lämpötila (degC)": 16.3
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 12,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 18.5,
    "Ylin lämpötila (degC)": 21.1,
    "Alin lämpötila (degC)": 17.3
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 13,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.5,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 18,
    "Ylin lämpötila (degC)": 20.3,
    "Alin lämpötila (degC)": 16.4
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 14,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 17.4,
    "Ylin lämpötila (degC)": 19.8,
    "Alin lämpötila (degC)": 16.1
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 15,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 1.2,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 17.3,
    "Ylin lämpötila (degC)": 20.6,
    "Alin lämpötila (degC)": 14.5
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 16,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 16.8,
    "Ylin lämpötila (degC)": 20.2,
    "Alin lämpötila (degC)": 12.7
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 17,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 18.6,
    "Ylin lämpötila (degC)": 22.2,
    "Alin lämpötila (degC)": 16.8
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 18,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 3.7,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 18.8,
    "Ylin lämpötila (degC)": 21.4,
    "Alin lämpötila (degC)": 16.7
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 19,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 2,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 17.7,
    "Ylin lämpötila (degC)": 19.7,
    "Alin lämpötila (degC)": 15.9
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 20,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 17.8,
    "Ylin lämpötila (degC)": 20.5,
    "Alin lämpötila (degC)": 15.1
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 21,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 17.3,
    "Ylin lämpötila (degC)": 19.4,
    "Alin lämpötila (degC)": 16.3
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 22,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 50.2,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 17.2,
    "Ylin lämpötila (degC)": 21.1,
    "Alin lämpötila (degC)": 12.9
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 23,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 12.3,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 16.1,
    "Ylin lämpötila (degC)": 19.4,
    "Alin lämpötila (degC)": 13
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 24,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 17.3,
    "Ylin lämpötila (degC)": 21.4,
    "Alin lämpötila (degC)": 14.4
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 25,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 16.5,
    "Ylin lämpötila (degC)": 20.2,
    "Alin lämpötila (degC)": 10.3
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 26,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 19,
    "Ylin lämpötila (degC)": 22.6,
    "Alin lämpötila (degC)": 15.3
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 27,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 17.9,
    "Ylin lämpötila (degC)": 21.2,
    "Alin lämpötila (degC)": 14.1
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 28,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 18.8,
    "Ylin lämpötila (degC)": 23.1,
    "Alin lämpötila (degC)": 14
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 29,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 3.5,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 19.8,
    "Ylin lämpötila (degC)": 22.2,
    "Alin lämpötila (degC)": 16.8
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 30,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 18.8,
    "Ylin lämpötila (degC)": 21.1,
    "Alin lämpötila (degC)": 17.7
  },
  {
    "Vuosi": 2019,
    "Kk": 8,
    "Pv": 31,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 17.8,
    "Ylin lämpötila (degC)": 20.5,
    "Alin lämpötila (degC)": 14.1
  },
  {
    "Vuosi": 2019,
    "Kk": 9,
    "Pv": 1,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 18.3,
    "Ylin lämpötila (degC)": 21.6,
    "Alin lämpötila (degC)": 15.3
  },
  {
    "Vuosi": 2019,
    "Kk": 9,
    "Pv": 2,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 8.2,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 17.9,
    "Ylin lämpötila (degC)": 22.5,
    "Alin lämpötila (degC)": 14.3
  },
  {
    "Vuosi": 2019,
    "Kk": 9,
    "Pv": 3,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 15.4,
    "Ylin lämpötila (degC)": 18.8,
    "Alin lämpötila (degC)": 12.9
  },
  {
    "Vuosi": 2019,
    "Kk": 9,
    "Pv": 4,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 16.4,
    "Ylin lämpötila (degC)": 20.2,
    "Alin lämpötila (degC)": 11.3
  },
  {
    "Vuosi": 2019,
    "Kk": 9,
    "Pv": 5,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 4.9,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 16.5,
    "Ylin lämpötila (degC)": 19.7,
    "Alin lämpötila (degC)": 12.7
  },
  {
    "Vuosi": 2019,
    "Kk": 9,
    "Pv": 6,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.9,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 15.1,
    "Ylin lämpötila (degC)": 17.2,
    "Alin lämpötila (degC)": 13.5
  },
  {
    "Vuosi": 2019,
    "Kk": 9,
    "Pv": 7,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 3.6,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 14.1,
    "Ylin lämpötila (degC)": 18.3,
    "Alin lämpötila (degC)": 9.8
  },
  {
    "Vuosi": 2019,
    "Kk": 9,
    "Pv": 8,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.9,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 15.7,
    "Ylin lämpötila (degC)": 17,
    "Alin lämpötila (degC)": 12.5
  },
  {
    "Vuosi": 2019,
    "Kk": 9,
    "Pv": 9,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 3.5,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 16.8,
    "Ylin lämpötila (degC)": 18.7,
    "Alin lämpötila (degC)": 14.8
  },
  {
    "Vuosi": 2019,
    "Kk": 9,
    "Pv": 10,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 18.9,
    "Ylin lämpötila (degC)": 21.1,
    "Alin lämpötila (degC)": 15.7
  },
  {
    "Vuosi": 2019,
    "Kk": 9,
    "Pv": 11,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 4.3,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 16.6,
    "Ylin lämpötila (degC)": 20.4,
    "Alin lämpötila (degC)": 15
  },
  {
    "Vuosi": 2019,
    "Kk": 9,
    "Pv": 12,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.4,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 15.8,
    "Ylin lämpötila (degC)": 17.2,
    "Alin lämpötila (degC)": 14.9
  },
  {
    "Vuosi": 2019,
    "Kk": 9,
    "Pv": 13,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 8.5,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 13.1,
    "Ylin lämpötila (degC)": 16.5,
    "Alin lämpötila (degC)": 11.1
  },
  {
    "Vuosi": 2019,
    "Kk": 9,
    "Pv": 14,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 8.9,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 11,
    "Ylin lämpötila (degC)": 14.6,
    "Alin lämpötila (degC)": 9
  },
  {
    "Vuosi": 2019,
    "Kk": 9,
    "Pv": 15,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 13.3,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 11,
    "Ylin lämpötila (degC)": 13.5,
    "Alin lämpötila (degC)": 6.6
  },
  {
    "Vuosi": 2019,
    "Kk": 9,
    "Pv": 16,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 1.6,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 10.6,
    "Ylin lämpötila (degC)": 14.1,
    "Alin lämpötila (degC)": 9
  },
  {
    "Vuosi": 2019,
    "Kk": 9,
    "Pv": 17,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 8.9,
    "Ylin lämpötila (degC)": 11.9,
    "Alin lämpötila (degC)": 5.8
  },
  {
    "Vuosi": 2019,
    "Kk": 9,
    "Pv": 18,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 8.7,
    "Ylin lämpötila (degC)": 13.5,
    "Alin lämpötila (degC)": 6.9
  },
  {
    "Vuosi": 2019,
    "Kk": 9,
    "Pv": 19,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 6.6,
    "Ylin lämpötila (degC)": 11.9,
    "Alin lämpötila (degC)": 2
  },
  {
    "Vuosi": 2019,
    "Kk": 9,
    "Pv": 20,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 1.9,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 7.1,
    "Ylin lämpötila (degC)": 11.5,
    "Alin lämpötila (degC)": 1.6
  },
  {
    "Vuosi": 2019,
    "Kk": 9,
    "Pv": 21,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.7,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 8.9,
    "Ylin lämpötila (degC)": 10.9,
    "Alin lämpötila (degC)": 6.1
  },
  {
    "Vuosi": 2019,
    "Kk": 9,
    "Pv": 22,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 6.7,
    "Ylin lämpötila (degC)": 10.6,
    "Alin lämpötila (degC)": 3.8
  },
  {
    "Vuosi": 2019,
    "Kk": 9,
    "Pv": 23,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 5.7,
    "Ylin lämpötila (degC)": 10.6,
    "Alin lämpötila (degC)": 1.4
  },
  {
    "Vuosi": 2019,
    "Kk": 9,
    "Pv": 24,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 3.3,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 7.2,
    "Ylin lämpötila (degC)": 10,
    "Alin lämpötila (degC)": 3.6
  },
  {
    "Vuosi": 2019,
    "Kk": 9,
    "Pv": 25,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.8,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 7.4,
    "Ylin lämpötila (degC)": 8.6,
    "Alin lämpötila (degC)": 7.1
  },
  {
    "Vuosi": 2019,
    "Kk": 9,
    "Pv": 26,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 8.4,
    "Ylin lämpötila (degC)": 13.1,
    "Alin lämpötila (degC)": 3.7
  },
  {
    "Vuosi": 2019,
    "Kk": 9,
    "Pv": 27,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 9,
    "Ylin lämpötila (degC)": 13.7,
    "Alin lämpötila (degC)": 4.2
  },
  {
    "Vuosi": 2019,
    "Kk": 9,
    "Pv": 28,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 1.7,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 11.8,
    "Ylin lämpötila (degC)": 14.2,
    "Alin lämpötila (degC)": 9.6
  },
  {
    "Vuosi": 2019,
    "Kk": 9,
    "Pv": 29,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.9,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 12.5,
    "Ylin lämpötila (degC)": 14.4,
    "Alin lämpötila (degC)": 10.9
  },
  {
    "Vuosi": 2019,
    "Kk": 9,
    "Pv": 30,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 8,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 12.7,
    "Ylin lämpötila (degC)": 14.5,
    "Alin lämpötila (degC)": 11.7
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 1,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 2.1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 8.2,
    "Ylin lämpötila (degC)": 12.9,
    "Alin lämpötila (degC)": 5.2
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 2,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.5,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 6.9,
    "Ylin lämpötila (degC)": 9.9,
    "Alin lämpötila (degC)": 4.1
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 3,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 2.5,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 4.5,
    "Ylin lämpötila (degC)": 6.6,
    "Alin lämpötila (degC)": 3.4
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 4,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.9,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 2.4,
    "Ylin lämpötila (degC)": 5.3,
    "Alin lämpötila (degC)": 1.5
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 5,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 2.5,
    "Ylin lämpötila (degC)": 5.8,
    "Alin lämpötila (degC)": -0.2
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 6,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 4,
    "Ylin lämpötila (degC)": 6.9,
    "Alin lämpötila (degC)": 0.3
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 7,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 4.5,
    "Ylin lämpötila (degC)": 7.9,
    "Alin lämpötila (degC)": 2.7
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 8,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 5,
    "Ylin lämpötila (degC)": 7.2,
    "Alin lämpötila (degC)": 2.4
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 9,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 1.1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 4.8,
    "Ylin lämpötila (degC)": 7.6,
    "Alin lämpötila (degC)": 1.9
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 10,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 2.4,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 7.1,
    "Ylin lämpötila (degC)": 10.2,
    "Alin lämpötila (degC)": 4.8
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 11,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 33.8,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 10.4,
    "Ylin lämpötila (degC)": 12.3,
    "Alin lämpötila (degC)": 5.7
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 12,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 9.8,
    "Ylin lämpötila (degC)": 11.5,
    "Alin lämpötila (degC)": 8.2
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 13,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 1.4,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 8.9,
    "Ylin lämpötila (degC)": 12.2,
    "Alin lämpötila (degC)": 6.4
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 14,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 9.3,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 5,
    "Ylin lämpötila (degC)": 8.5,
    "Alin lämpötila (degC)": 2.4
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 15,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 4.4,
    "Ylin lämpötila (degC)": 7.8,
    "Alin lämpötila (degC)": -1.1
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 16,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 6.8,
    "Ylin lämpötila (degC)": 8.3,
    "Alin lämpötila (degC)": 5
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 17,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 3.6,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 5.1,
    "Ylin lämpötila (degC)": 5.6,
    "Alin lämpötila (degC)": 4.6
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 18,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 3,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 8,
    "Ylin lämpötila (degC)": 10.3,
    "Alin lämpötila (degC)": 4.8
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 19,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 2.9,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 11.5,
    "Ylin lämpötila (degC)": 12.4,
    "Alin lämpötila (degC)": 10.3
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 20,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 13.3,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 9.9,
    "Ylin lämpötila (degC)": 11.3,
    "Alin lämpötila (degC)": 7.6
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 21,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.2,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 6.7,
    "Ylin lämpötila (degC)": 10.7,
    "Alin lämpötila (degC)": 4.4
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 22,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 9.6,
    "Ylin lämpötila (degC)": 11.4,
    "Alin lämpötila (degC)": 2.8
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 23,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 10.1,
    "Ylin lämpötila (degC)": 11.9,
    "Alin lämpötila (degC)": 8.1
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 24,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 11.1,
    "Ylin lämpötila (degC)": 12.1,
    "Alin lämpötila (degC)": 10.5
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 25,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.6,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 10.7,
    "Ylin lämpötila (degC)": 12.1,
    "Alin lämpötila (degC)": 9.7
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 26,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 13.2,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 7.5,
    "Ylin lämpötila (degC)": 11.6,
    "Alin lämpötila (degC)": 5.8
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 27,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 9.7,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 3.2,
    "Ylin lämpötila (degC)": 5.7,
    "Alin lämpötila (degC)": 1.1
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 28,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.8,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 0.9,
    "Ylin lämpötila (degC)": 2.8,
    "Alin lämpötila (degC)": 0.1
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 29,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": -1,
    "Ylin lämpötila (degC)": 1.4,
    "Alin lämpötila (degC)": -3
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 30,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": -0.4,
    "Ylin lämpötila (degC)": 1.6,
    "Alin lämpötila (degC)": -3.4
  },
  {
    "Vuosi": 2019,
    "Kk": 10,
    "Pv": 31,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": "",
    "Ilman lämpötila (degC)": 4.7,
    "Ylin lämpötila (degC)": 5.9,
    "Alin lämpötila (degC)": 1.4
  },
  {
    "Vuosi": 2019,
    "Kk": 11,
    "Pv": 1,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 1.4,
    "Ylin lämpötila (degC)": 4.8,
    "Alin lämpötila (degC)": -0.4
  },
  {
    "Vuosi": 2019,
    "Kk": 11,
    "Pv": 2,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 4.2,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 5,
    "Ylin lämpötila (degC)": 6.5,
    "Alin lämpötila (degC)": -1.1
  },
  {
    "Vuosi": 2019,
    "Kk": 11,
    "Pv": 3,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 3.3,
    "Ylin lämpötila (degC)": 5.3,
    "Alin lämpötila (degC)": 1.1
  },
  {
    "Vuosi": 2019,
    "Kk": 11,
    "Pv": 4,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": -0.5,
    "Ylin lämpötila (degC)": 2.6,
    "Alin lämpötila (degC)": -1.4
  },
  {
    "Vuosi": 2019,
    "Kk": 11,
    "Pv": 5,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": -1.2,
    "Ylin lämpötila (degC)": 0.6,
    "Alin lämpötila (degC)": -2.4
  },
  {
    "Vuosi": 2019,
    "Kk": 11,
    "Pv": 6,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.4,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": -2.5,
    "Ylin lämpötila (degC)": -0.6,
    "Alin lämpötila (degC)": -3.7
  },
  {
    "Vuosi": 2019,
    "Kk": 11,
    "Pv": 7,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 0.8,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": -1.5,
    "Ylin lämpötila (degC)": 1.3,
    "Alin lämpötila (degC)": -3.7
  },
  {
    "Vuosi": 2019,
    "Kk": 11,
    "Pv": 8,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 1,
    "Lumensyvyys (cm)": 2,
    "Ilman lämpötila (degC)": 1.7,
    "Ylin lämpötila (degC)": 5.2,
    "Alin lämpötila (degC)": -0.8
  },
  {
    "Vuosi": 2019,
    "Kk": 11,
    "Pv": 9,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 4.7,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 6.5,
    "Ylin lämpötila (degC)": 7.1,
    "Alin lämpötila (degC)": 5.2
  },
  {
    "Vuosi": 2019,
    "Kk": 11,
    "Pv": 10,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": 7.8,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 7.6,
    "Ylin lämpötila (degC)": 8.9,
    "Alin lämpötila (degC)": 5.8
  },
  {
    "Vuosi": 2019,
    "Kk": 11,
    "Pv": 11,
    "Klo": "00:00",
    "Aikavyöhyke": "UTC",
    "Sademäärä (mm)": -1,
    "Lumensyvyys (cm)": -1,
    "Ilman lämpötila (degC)": 0.6,
    "Ylin lämpötila (degC)": 8,
    "Alin lämpötila (degC)": -0.7
  }];

  var dataWithDate = chart.data.map(function (e) {
    var o = Object.assign({}, e);
    var regEx = /\b\d\b/g;
    var kkToS = e.Kk.toString();
    var pvToS = e.Pv.toString();
    if (kkToS.match(regEx) && pvToS.match(regEx)) {
      o.date = e.Vuosi + "-0" + e.Kk + "-0" + e.Pv;
    } else {
      o.date = e.Vuosi + "-" + e.Kk + "-" + e.Pv;
    }
    return o;
  })

  console.log(dataWithDate);

  chart.data = dataWithDate;

  // Create axes
  var dateAxis = chart.xAxes.push(new am4charts.DateAxis());
  //dateAxis.renderer.grid.template.location = 0;
  //dateAxis.renderer.minGridDistance = 30;

  var valueAxis1 = chart.yAxes.push(new am4charts.ValueAxis());
  valueAxis1.title.text = "Sademäärä";

  var valueAxis2 = chart.yAxes.push(new am4charts.ValueAxis());
  valueAxis2.title.text = "Ilman lämpötila";
  valueAxis2.renderer.opposite = true;
  valueAxis2.renderer.grid.template.disabled = true;

  // Create series
  var series1 = chart.series.push(new am4charts.ColumnSeries());
  series1.dataFields.valueY = "Sademäärä (mm)";
  series1.dataFields.dateX = "date";
  series1.yAxis = valueAxis1;
  series1.name = "Sademäärä (mm)";
  series1.tooltipText = "{name}\n[bold font-size: 20]{valueY} mm[/]";
  series1.fill = chart.colors.getIndex(1);
  series1.strokeWidth = 0;
  series1.clustered = false;
  series1.toBack();

  var series2 = chart.series.push(new am4charts.ColumnSeries());
  series2.dataFields.valueY = "Lumensyvyys (cm)";
  series2.dataFields.dateX = "date";
  series2.yAxis = valueAxis1;
  series2.name = "Lumensyvyys (cm)";
  series2.tooltipText = "{name}\n[bold font-size: 20]{valueY} cm[/]";
  series2.fill = chart.colors.getIndex(2).lighten(0.5);
  series2.strokeWidth = 0;
  series2.clustered = false;
  series2.columns.template.width = am4core.percent(30);

  var series3 = chart.series.push(new am4charts.LineSeries());
  series3.dataFields.valueY = "Ilman lämpötila (degC)";
  series3.dataFields.dateX = "date";
  series3.name = "Ilman lämpötila (°C)";
  series3.strokeWidth = 2;
  series3.tensionX = 0.7;
  series3.yAxis = valueAxis2;
  series3.tooltipText = "{name}\n[bold font-size: 20]{valueY} °C[/]";
  series3.stroke = chart.colors.getIndex(5);

  var bullet3 = series3.bullets.push(new am4charts.CircleBullet());
  bullet3.circle.radius = 3;
  bullet3.circle.strokeWidth = 2;
  bullet3.circle.fill = am4core.color("#fff");

  var series4 = chart.series.push(new am4charts.LineSeries());
  series4.dataFields.valueY = "Ylin lämpötila (degC)";
  series4.dataFields.dateX = "date";
  series4.name = "Ylin lämpötila";
  series4.strokeWidth = 2;
  series4.tensionX = 0.7;
  series4.yAxis = valueAxis2;
  series4.tooltipText = "{name}\n[bold font-size: 20]{valueY} °C[/]";
  series4.stroke = chart.colors.getIndex(9);
  // series4.strokeDasharray = "3,3";

  var bullet4 = series4.bullets.push(new am4charts.CircleBullet());
  bullet4.circle.radius = 3;
  bullet4.circle.strokeWidth = 2;
  bullet4.circle.fill = am4core.color("#fff");

  var series5 = chart.series.push(new am4charts.LineSeries());
  series5.dataFields.valueY = "Alin lämpötila (degC)";
  series5.dataFields.dateX = "date";
  series5.name = "Alin lämpötila";
  series5.strokeWidth = 2;
  series5.tensionX = 0.7;
  series5.yAxis = valueAxis2;
  series5.tooltipText = "{name}\n[bold font-size: 20]{valueY} °C[/]";
  series5.stroke = chart.colors.getIndex(2);
  // series5.strokeDasharray = "3,3";

  var bullet5 = series5.bullets.push(new am4charts.CircleBullet());
  bullet5.circle.radius = 3;
  bullet5.circle.strokeWidth = 2;
  bullet5.circle.fill = am4core.color("#fff");

  // Add cursor
  chart.cursor = new am4charts.XYCursor();

  // Add legend
  chart.legend = new am4charts.Legend();
  chart.legend.position = "top";

  // Add scrollbar
  chart.scrollbarX = new am4charts.XYChartScrollbar();
  chart.scrollbarX.series.push(series1);
  chart.scrollbarX.series.push(series3);
  chart.scrollbarX.parent = chart.bottomAxesContainer;

});
